default: &default
  adapter: postgresql
  encoding: unicode
  # CircleCI requires that we use double-quotes here, otherwise
  # the command CircleCI uses to create database.yml fails.
  database: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_DATABASE") %>
  host: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_HOST") %>
  password: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_PASSWORD") %>
  username: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_USERNAME") %>
  pool: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_POOL", 5) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
