default: &default
  adapter: postgresql
  encoding: utf8
  # CircleCI requires that we use double-quotes here, otherwise
  # the command CircleCI uses to create database.yml fails.
  host: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_HOST", nil) %>
  password: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_PASSWORD", nil) %>
  username: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_USERNAME", nil) %>
  pool: <%= ENV.fetch("DEFENCE_SOLICITOR_DATABASE_POOL", 5) %>

development:
  <<: *default
  database: defence-solicitor_development

test:
  <<: *default
  database: defence-solicitor_test
