devise:
  key: <%= ENV["DEVISE_KEY"] %>
  salt: <%= ENV["DEVISE_SALT"] %>
rails:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
dsds:
  app_title: 'Defence Solicitor Deployment Service'
  dashboard_refresh_seconds: 3000
  solicitor_search_domain: "http://solicitor-search.herokuapp.com"
